language: node_js # 设置语言
node_js: stable # 设置相应版本
install:
    - npm install # 安装hexo及插件
    - npm install cheerio@0.22.0 --save
    - npm install hexo-renderer-pug hexo-renderer-stylus --save or yarn add hexo-renderer-pug hexo-renderer-stylus
script:
    - hexo clean # 清除
    - hexo g # 生成
after_script:
    - cd ./public
    - git init
    - git config user.name "onism68" # 修改name
    - git config user.email "onism68@gmail.com" # 修改email
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${githubToken}@${GH_REF}" master:master # GH_TOKEN是在Travis中配置token的名称
branches:
    only:
        - hexo-source #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
    global:
        - GH_REF: github.com/onism68/onism68.github.io.git #设置GH_REF，注意更改yourname